require_relative "Calendar"
require_relative "Efficiency"
require_relative "Popularity"
 
puts "The most sugar was produces from #{Sugar::most_sugar} pollen"
puts "The most efficient bee is #{Efficiency::most_efficient}"
puts "The least efficient bee is #{Efficiency::least_efficient}"
puts "The most popular pollen was #{Popularity::popular}"
puts "The best day for harvest was #{Calendar::best_day}"
puts "The worst day for harvest was #{Calendar::worst_day}"